### ISSUE TITLE
Error on dependency install wrtc

### ISSUE THREAD

**Issue by jairsnow** [geckosio/simple-chat-app-example#2]
OS: Ubuntu 18.04.4
Node version: v12.18.1

When i try to run npm i to install all the dependency i get the following error:

```
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: bad download
node-pre-gyp ERR! stack     at Unpack.afterTarball (/var/nodejs/simple-chat-app-example/node_modules/node-pre-gyp/lib/install.js:100:46)
node-pre-gyp ERR! stack     at Unpack.emit (events.js:315:20)
node-pre-gyp ERR! stack     at Unpack.[maybeClose] (/var/nodejs/simple-chat-app-example/node_modules/tar/lib/unpack.js:171:12)
node-pre-gyp ERR! stack     at Unpack.[unpend] (/var/nodejs/simple-chat-app-example/node_modules/tar/lib/unpack.js:394:21)
node-pre-gyp ERR! stack     at /var/nodejs/simple-chat-app-example/node_modules/tar/lib/unpack.js:308:46
node-pre-gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:155:23)
node-pre-gyp ERR! System Linux 4.15.0-74-generic
node-pre-gyp ERR! command "/usr/bin/node" "/var/nodejs/simple-chat-app-example/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /var/nodejs/simple-chat-app-example/node_modules/wrtc
node-pre-gyp ERR! node -v v12.18.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
bad download
npm WARN chat-app-example@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.4.2 install: `node scripts/download-prebuilt.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.4.2 install script.

```
Seems like npm cannot resolve/download the wrtc package.

**Comment by yandeu** [comment]
Looks like the binary for wrtc v0.4.2 is not available anymore. I will update the example to latest geckos.io version. Hopefully this will solve the issue.

**Comment by yandeu** [comment]
Done! And it works :)
